package com.binarylabyrinth.orderservice.dto;

import lombok.*;

import java.time.LocalDateTime;

/**
 * OrderResponseDto - API Response Data Transfer Object
 *
 * This DTO represents the data structure returned in API responses
 * for order operations (GET, POST).
 *
 * Includes all order details generated by the server:
 * - Order ID (database primary key)
 * - Order Number (UUID-based, customer-visible reference)
 * - Creation timestamp
 *
 * Used by: All OrderController GET/POST endpoints
 *
 * Example JSON Response:
 * {
 *   "id": 1,
 *   "orderNumber": "ORD-550e8400-e29b-41d4-a716-446655440000",
 *   "productId": "507f1f77bcf86cd799439011",
 *   "quantity": 2,
 *   "price": 199.98,
 *   "createdAt": "2026-05-18T10:30:00"
 * }
 *
 * @author Binary Labyrinth
 * @version 1.0
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderResponseDto {

    /** Database primary key - auto-generated by MySQL */
    private Long id;

    /** Customer reference - UUID-based unique order number */
    private String orderNumber;

    /** User ID who placed the order */
    private String userId;

    /** Product ID being ordered */
    private String productId;

    /** Quantity ordered */
    private Integer quantity;

    /** Total order price */
    private Double price;

    /** Order status: PLACED, CONFIRMED, CANCELLED, SHIPPED, DELIVERED */
    private String status;

    /** Timestamp of when the order was created */
    private LocalDateTime createdAt;
}