apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-config.yaml
  - platform-services.yaml
  - discovery-server.yaml
  - config-server.yaml
  - api-gateway.yaml
  - product-service.yaml
  - order-service.yaml
  - inventory-service.yaml
  - notification-service.yaml
