apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: online-shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: online-shopping/order-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: ORDER_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_DATASOURCE_URL
            - name: ORDER_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ORDER_DATASOURCE_USERNAME
            - name: ORDER_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ORDER_DATASOURCE_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_DEFAULT_ZONE
            - name: JPA_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JPA_DDL_AUTO
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 35
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 70
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: online-shopping
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
