package com.binarylabyrinth.orderservice.mapper;

import com.binarylabyrinth.orderservice.dto.OrderRequestDto;
import com.binarylabyrinth.orderservice.dto.OrderResponseDto;
import com.binarylabyrinth.orderservice.entity.Order;
import org.springframework.stereotype.Component;

/**
 * OrderMapper - Data Transfer Object Mapper
 *
 * Responsible for converting between different data representations:
 * - OrderRequestDto (API input) ↔ Order (Entity)
 * - Order (Entity) ↔ OrderResponseDto (API output)
 *
 * Important: OrderNumber and CreatedAt are NOT mapped from request
 * These are generated by the service and database respectively
 *
 * Benefits of mapper pattern:
 * - Decouples DTOs from entities
 * - Central place for transformation logic
 * - Easy to modify field mappings
 * - Supports different representations for different use cases
 *
 * @author Binary Labyrinth
 * @version 1.0
 */
@Component
public class OrderMapper {

    /**
     * Convert OrderRequestDto to Order Entity
     * Used when placing a new order from API request
     *
     * Note: OrderNumber and CreatedAt are NOT set here
     * - OrderNumber is set in OrderServiceImpl (UUID.randomUUID)
     * - CreatedAt is set in OrderServiceImpl (LocalDateTime.now())
     */
    public Order toEntity(OrderRequestDto requestDto){

        return Order.builder()
                .userId(requestDto.getUserId())
                .productId(requestDto.getProductId())
                .quantity(requestDto.getQuantity())
                .price(requestDto.getPrice())
                .build();
    }

    /**
     * Convert Order Entity to OrderResponseDto
     * Used when returning order data to API client
     * Includes all order details from database
     */
    public OrderResponseDto toResponseDto(Order order){

        return OrderResponseDto.builder()
                .id(order.getId())
                .orderNumber(order.getOrderNumber())
                .userId(order.getUserId())
                .productId(order.getProductId())
                .quantity(order.getQuantity())
                .price(order.getPrice())
                .status(order.getStatus())
                .createdAt(order.getCreatedAt())
                .build();
    }
}