-- ========================================
-- MySQL Database Initialization Script
-- ========================================
--
-- This script initializes MySQL databases for the Online Shopping microservices
-- It runs automatically when the MySQL Docker container starts (first run)
--
-- DATABASES CREATED:
-- 1. order_service - Order Service database
-- 2. inventory_service - Inventory Service database
-- 3. notification_service - Notification Service database
--
-- AUTO-SETUP:
-- - If database doesn't exist, it's created
-- - Tables are auto-generated by JPA/Hibernate on service startup
-- - Spring Data: spring.jpa.hibernate.ddl-auto=update or create-drop
--
-- DATABASE SCHEMAS (auto-generated by services):
--
-- order_service.orders table:
--   - id: bigint (auto-increment primary key)
--   - order_number: varchar (UUID)
--   - product_id: varchar (product identifier)
--   - quantity: int
--   - price: double (total order price)
--   - status: varchar (PLACED, CONFIRMED, SHIPPED, DELIVERED, CANCELLED)
--   - created_at: datetime
--
-- inventory_service.inventory table:
--   - id: bigint (auto-increment primary key)
--   - product_id: varchar (unique)
--   - quantity: int (stock levels)
--
-- notification_service.notification table:
--   - id: bigint (auto-increment primary key)
--   - recipient: varchar (email/phone)
--   - subject: varchar
--   - message: longtext
--   - type: varchar (EMAIL, SMS, PUSH)
--   - status: varchar (PENDING, SENT, FAILED)
--   - error_message: varchar (failure reason)
--   - created_at: datetime
--   - sent_at: datetime
--
-- MANUAL DATA INSERT (optional):
-- After services start, you can manually insert test data:
--
-- INSERT INTO order_service.orders (order_number, product_id, quantity, price, status, created_at)
-- VALUES ('ORDER-001', 'PROD-001', 2, 99.99, 'PLACED', NOW());
--
-- INSERT INTO inventory_service.inventory (product_id, quantity)
-- VALUES ('PROD-001', 100);
--

-- ========================================
-- CREATE DATABASE FOR ORDER SERVICE
-- ========================================
-- Database for managing orders (Order Service)
-- IF NOT EXISTS: Don't error if database already exists
CREATE DATABASE IF NOT EXISTS order_service;

-- ========================================
-- CREATE DATABASE FOR INVENTORY SERVICE
-- ========================================
-- Database for managing inventory (Inventory Service)
CREATE DATABASE IF NOT EXISTS inventory_service;

-- ========================================
-- CREATE DATABASE FOR NOTIFICATION SERVICE
-- ========================================
-- Database for managing notifications (Notification Service)
CREATE DATABASE IF NOT EXISTS notification_service;

-- ========================================
-- CREATE DATABASE FOR USER SERVICE
-- ========================================
-- Database for managing users and authentication (User Service)
CREATE DATABASE IF NOT EXISTS user_service;

-- ========================================
-- CREATE DATABASE FOR PAYMENT SERVICE
-- ========================================
-- Database for managing payments (Payment Service)
CREATE DATABASE IF NOT EXISTS payment_service;

-- ========================================
-- CREATE DATABASE FOR CART SERVICE
-- ========================================
-- Database for managing shopping carts (Cart Service)
CREATE DATABASE IF NOT EXISTS cart_service;

-- ========================================
-- CREATE DATABASE FOR REVIEW SERVICE
-- ========================================
-- Database for managing product reviews and ratings (Review Service)
CREATE DATABASE IF NOT EXISTS review_service;

-- ========================================
-- CREATE DATABASE FOR RECOMMENDATION SERVICE
-- ========================================
-- Database for storing user-product interaction history (Recommendation Service)
CREATE DATABASE IF NOT EXISTS recommendation_service;

-- ========================================
-- ALTERNATIVE: Create with specific character set
-- ========================================
-- For production, specify UTF-8 encoding:
-- CREATE DATABASE IF NOT EXISTS order_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE DATABASE IF NOT EXISTS inventory_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE DATABASE IF NOT EXISTS notification_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE DATABASE IF NOT EXISTS user_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE DATABASE IF NOT EXISTS payment_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE DATABASE IF NOT EXISTS cart_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
--


